const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
  {
    id: '01e8b4e2-803c-498d-9e06-0919c1d08e0b',
    name: 'Userisha',
    email: 'email@email.com',
    password: '123456',
  },
];

const talents = [
  {
    id: '1c23a193-d817-494b-a798-efb2202265f9',
    name: 'Kai Tanaka',
    email: 'kai.tanaka@creatives.io',
    image_url: '/talent/ladystockdj.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: '85a12328-94ab-4222-b502-72c59540c793',
    name: 'Elena Garcia',
    email: 'elena.garcia@stagelights.co',
    image_url: '/talent/ladystockdj2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: '630eb7fe-5902-4100-9fa6-40b7632e678f',
    name: 'Alex Chen',
    email: 'alex.chen@beatsandbreaks.net',
    image_url: '/talent/ladystockdj.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: '01ca724c-2231-40f9-8422-88023b593105',
    name: 'Riley Jones',
    email: 'riley.jones@vinylvibes.com',
    image_url: '/talent/manstockdj.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: 'e9635b1a-679b-4715-98ab-23f157d1971c',
    name: 'Samir Hussain',
    email: 'samir.hussain@turntabletunes.xyz',
    image_url: '/talent/manstockdj2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: '42fa6482-920a-42d6-b075-95d813a8b164',
    name: 'Maya Rodriguez',
    email: 'maya.rodriguez@rhythmriots.io',
    image_url: '/talent/ladystockdj2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: '9721b4c1-53f0-49d0-916a-7112647a5538',
    name: 'Liam Connor',
    email: 'liam.connor@spinmasters.co',
    image_url: '/talent/manstockdj.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: '3fa6215b-1115-46c0-8709-9a8512d7650a',
    name: 'Ava Singh',
    email: 'ava.singh@mixmasters.biz',
    image_url: '/talent/ladystockdj2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: 'f2581be9-24e0-4e0c-a158-02f71730a368',
    name: 'Noah Lee',
    email: 'noah.lee@groovegarden.com',
    image_url: '/talent/manstockdj2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: 'd5137be2-a427-4636-a13a-97a46f714002',
    email: 'sofia.miranda@soundwavecollective.net',
    name: 'Sofia Miranda',
    image_url: '/talent/ladystockdj2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'DJ',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    name: 'Lee Robinson',
    email: 'lee@robinson.com',
    image_url: '/talent/ladymusician.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '6f112b24-3db2-4ecb-83e1-9a4e307e1371',
    name: 'Emily White',
    email: 'emily@white.com',
    image_url: '/talent/ladymusician.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: 'bcbfead5-63d5-4d0f-925e-0c0c0aafe0e1',
    name: 'Alex Turner',
    email: 'alex@turner.com',
    image_url: '/talent/manmusician2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: 'cfdb1b87-8a2f-4a8b-a8bf-0f8e1e5b2eb1',
    name: 'Sophie Davis',
    email: 'sophie@davis.com',
    image_url: '/talent/ladymusician.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: 'eb974ef2-71d4-4dbd-a6a0-f21d013df13d',
    name: 'Ethan Clark',
    email: 'ethan@clark.com',
    image_url: '/talent/manmusician2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '7a10d1f9-3a8e-4f79-aa91-cbe4d44e8823',
    name: 'Olivia Moore',
    email: 'olivia@moore.com',
    image_url: '/talent/ladymusician.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '2e25ec5d-4370-45ea-a56b-68e01d34293a',
    name: 'Benjamin King',
    email: 'benjamin@king.com',
    image_url: '/talent/musicianman.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '38c7f127-8d7d-45d8-aa2a-b40c9995c442',
    name: 'Mia Garcia',
    email: 'mia@garcia.com',
    image_url: '/talent/ladymusician.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: 'f539759e-cb27-4c32-9357-4f6fbbdc4de7',
    name: 'Jackson Reed',
    email: 'jackson@reed.com',
    image_url: '/talent/manmusician2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '57eb89af-3e8f-4d32-8d5b-1af58f8e4e6c',
    name: 'Isabella Lewis',
    email: 'isabella@lewis.com',
    image_url: '/talent/ladymusician.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '76af0102-5b7e-4683-9c11-1d936f5b3e86',
    name: 'Caleb Baker',
    email: 'caleb@baker.com',
    image_url: '/talent/musicianman.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '4c7782a2-7e6e-4e0b-ba78-0f1a2487b749',
    name: 'Hannah Hill',
    email: 'hannah@hill.com',
    image_url: '/talent/musicianman.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '42d5d9af-af95-4709-9ff7-515f9fb10c3a',
    name: 'Gabriel Taylor',
    email: 'gabriel@taylor.com',
    image_url: '/talent/manmusician2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '9933b157-b9b6-4a0d-8b61-4acbd8033a21',
    name: 'Lily Wright',
    email: 'lily@wright.com',
    image_url: '/talent/ladymusician.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '8d126047-3999-4201-a7cd-099a2c6a91a5',
    name: 'Daniel Martinez',
    email: 'daniel@martinez.com',
    image_url: '/talent/manmusician2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'musician',
  },
  {
    id: '7f23bc3a-8c5b-4957-b832-8cb5df27f7f1',
    name: 'Jordan Taylor',
    email: 'jordan@taylor.com',
    image_url: '/talent/videoperson.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'e593c98f-927c-43b2-9e6d-8f309961bfc7',
    name: 'Avery Lee',
    email: 'avery@lee.com',
    image_url: '/talent/videolady.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: '18c24813-b373-416a-b201-0485c98a695f',
    name: 'Cameron Rodriguez',
    email: 'cameron@rodriguez.com',
    image_url: '/talent/videoperson.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'a0a7a51d-347b-4e2d-947b-16f0831e76fc',
    name: 'Alexis James',
    email: 'alexis@james.com',
    image_url: '/talent/videolady.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: '2848011b-44ac-4a99-b4da-60fda4fc173f',
    name: 'Riley Smith',
    email: 'riley@smith.com',
    image_url: '/talent/manvideo.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'b3e6620d-5443-4f39-99f9-4e9c6144c93d',
    name: 'Taylor Morgan',
    email: 'taylor@morgan.com',
    image_url: '/talent/videoperson.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'e8e3e25a-0a97-488f-a065-8496a5a0c0b2',
    name: 'Morgan Patel',
    email: 'morgan@patel.com',
    image_url: '/talent/videolady.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'a39cc773-9519-43b2-8e72-54f9ec4d2069',
    name: 'Casey Williams',
    email: 'casey@williams.com',
    image_url: '/talent/manvideo.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: '1be7f85b-64c5-413e-9904-b92f39e9de52',
    name: 'Alex Morgan',
    email: 'alex@morgan.com',
    image_url: '/talent/videoperson.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'f44e58d5-168e-4fc2-b8e3-31b3ec51d0e2',
    name: 'Jordan Kim',
    email: 'jordan@kim.com',
    image_url: '/talent/videoperson.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: '6530cbb5-8a38-4f96-a7db-953b1f11be49',
    name: 'Dylan Anderson',
    email: 'dylan@anderson.com',
    image_url: '/talent/manvideo.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'e1231332-40e5-4d37-b918-6823b4de2d27',
    name: 'Morgan Bailey',
    email: 'morgan@bailey.com',
    image_url: '/talent/videoperson.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'a68d19a9-1b8d-4d80-a3d1-b754e0cf0e32',
    name: 'Harper Evans',
    email: 'harper@evans.com',
    image_url: '/talent/videolady.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: '1d9e0a49-86c1-46d4-a86a-b7f5798d7bf4',
    name: 'Ryan Taylor',
    email: 'ryan@taylor.com',
    image_url: '/talent/manvideo.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: 'c0c21e36-38e4-4b3e-af6b-8388f14be8ea',
    name: 'Jamie Robinson',
    email: 'jamie@robinson.com',
    image_url: '/talent/videolady.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'videographer',
  },
  {
    id: '6a9cf804-2421-4d60-8d92-c9e3ee2a1b9a',
    name: 'Elijah Evans',
    email: 'elijah.evans@example.com',
    image_url: '/talent/maledancer.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: 'c0c8454a-7a52-4b90-87c1-0d42c242f8a7',
    name: 'Sophia Nguyen',
    email: 'sophia.nguyen@example.com',
    image_url: '/talent/ladydancer.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: 'd873584f-af57-4e8d-a4b4-7625b890b847',
    name: 'Mia Robinson',
    email: 'mia.robinson@example.com',
    image_url: '/talent/ladydancer2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: 'c27301d5-75c2-4c18-89da-0703030bafaa',
    name: 'Olivia Baker',
    email: 'olivia.baker@example.com',
    image_url: '/talent/ladydancer.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: 'e44f14cf-ba97-4961-8b27-146af014c792',
    name: 'Noah Taylor',
    email: 'noah.taylor@example.com',
    image_url: '/talent/maledancer2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: '5c96a8b7-c8ed-4ea8-9bda-5f0755635c8e',
    name: 'Ella Lee',
    email: 'ella.lee@example.com',
    image_url: '/talent/ladydancer2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: '2e8e20cf-c229-4921-9388-7aebd9aa04ae',
    name: 'Caleb Kim',
    email: 'caleb.kim@example.com',
    image_url: '/talent/maledancer.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: 'd66655a7-b60f-4816-87b7-6a0c965249f2',
    name: 'Chloe Baker',
    email: 'chloe.baker@example.com',
    image_url: '/talent/ladydancer.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: '32d95f2c-5342-4bd9-86ea-40a8122a3ab8',
    name: 'Lucas Robinson',
    email: 'lucas.robinson@example.com',
    image_url: '/talent/maledancer2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: '55769c1b-bef9-4613-8bc9-2638137173e8',
    name: 'Emma White',
    email: 'emma.white@example.com',
    image_url: '/talent/ladydancer2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: '7792d6b4-6a3d-44cd-9d36-4008734e1077',
    name: 'Mia Taylor',
    email: 'mia.taylor@example.com',
    image_url: '/talent/ladydancer.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: '9e4e2282-ee2f-47ac-8cf8-6e7eb3fe8ecb',
    name: 'Aiden Taylor',
    email: 'aiden.taylor@example.com',
    image_url: '/talent/maledancer.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: '07b3d8c7-3d7b-4f8a-8b1f-789205cf8a90',
    name: 'Ava Baker',
    email: 'ava.baker@example.com',
    image_url: '/talent/ladydancer.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: 'd79f37d8-fc4d-493c-b300-c83d73a51279',
    name: 'Caleb Evans',
    email: 'caleb.evans@example.com',
    image_url: '/talent/maledancer2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: '92e5174d-d2b3-4a5b-9fbb-365d3e4c8e6e',
    name: 'Chloe Wilson',
    email: 'chloe.wilson@example.com',
    image_url: '/talent/ladydancer2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'dancer',
  },
  {
    id: 'f1a7c802-d3fe-4e6b-ae5f-273e1320aa43',
    name: 'Liam Miller',
    email: 'liam.miller@example.com',
    image_url: '/talent/guyphotog2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'a9cbf5e7-0f87-493f-b6d0-8d14c9f833f6',
    name: 'Olivia Davis',
    email: 'olivia.davis@example.com',
    image_url: '/talent/ladyphotog.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'e146c3ec-73dd-401b-8266-aa254fbd2f05',
    name: 'Elijah Thomas',
    email: 'elijah.thomas@example.com',
    image_url: '/talent/guyphotog2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'bc3a7cb2-0c75-4e5a-830b-6c4284dfdf8b',
    name: 'Sophia Martinez',
    email: 'sophia.martinez@example.com',
    image_url: '/talent/ladyphotog2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'e053f0b5-fb20-4d52-aa2e-5c305c05a873',
    name: 'Logan White',
    email: 'logan.white@example.com',
    image_url: '/talent/guyphotog.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'e7b64a85-c0f4-41cc-8a4c-936b195bf850',
    name: 'Ella Turner',
    email: 'ella.turner@example.com',
    image_url: '/talent/ladyphotog.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: '0c523feb-2ef4-4e37-8db4-9d5f9f6b6a67',
    name: 'Jackson Harris',
    email: 'jackson.harris@example.com',
    image_url: '/talent/guyphotog2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'f3bf7d72-6b7a-41b4-bb3a-b93658119843',
    name: 'Ava Robinson',
    email: 'ava.robinson@example.com',
    image_url: '/talent/ladyphotog.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: '3149a844-44ed-4da7-9db4-943eeebc98b1',
    name: 'Lucas Taylor',
    email: 'lucas.taylor@example.com',
    image_url: '/talent/guyphotog.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: '53702c6e-dc9f-4c2a-bb37-4147b10c9f64',
    name: 'Mia Lee',
    email: 'mia.lee@example.com',
    image_url: '/talent/ladyphotog2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'b1b04d34-a15e-4f9a-8bc5-07d0d6bb1a11',
    name: 'Aiden Smith',
    email: 'aiden.smith@example.com',
    image_url: '/talent/guyphotog2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: '3a4c55f9-9e5e-45b8-8d95-437cfa1fe134',
    name: 'Chloe Wilson',
    email: 'chloe.wilson@example.com',
    image_url: '/talent/ladyphotog.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: '2f1a743a-2e0d-4b2f-9363-7a3c5d001048',
    name: 'Noah Brown',
    email: 'noah.brown@example.com',
    image_url: '/talent/guyphotog.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'e75d98a4-df9c-4a2f-bc91-b17c5e2c7325',
    name: 'Emma Evans',
    email: 'emma.evans@example.com',
    image_url: '/talent/ladyphotog2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'b8f789d5-106e-4c5b-a2b4-4475e539f34b',
    name: 'Caleb Miller',
    email: 'caleb.miller@example.com',
    image_url: '/talent/guyphotog.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'photographer',
  },
  {
    id: 'b1a98fcd-4519-4c4c-a3b2-02f54052d06d',
    name: 'Liam Harris',
    email: 'liam.harris@example.com',
    image_url: '/talent/malebartender2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: '7f0a2c77-80e9-4ef3-b05c-2a3a05d7a6d5',
    name: 'Olivia Turner',
    email: 'olivia.turner@example.com',
    image_url: '/talent/ladybartender.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: '3d535450-d79f-4f0f-9ea4-6e8f2725f264',
    name: 'Elijah Davis',
    email: 'elijah.davis@example.com',
    image_url: '/talent/malebartender.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'a1549f6c-bff5-4470-aa8d-39ec287de034',
    name: 'Sophia Baker',
    email: 'sophia.baker@example.com',
    image_url: '/talent/ladybartender2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: '0bda1eac-9e3a-4c95-834b-09ad6e6c4c8e',
    name: 'Logan Martinez',
    email: 'logan.martinez@example.com',
    image_url: '/talent/malebartender2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'a26ea5bb-6e02-4a1e-b7cd-4e90e271d0c2',
    name: 'Ella Robinson',
    email: 'ella.robinson@example.com',
    image_url: '/talent/ladybartender.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: '3a8ec2cd-61d2-4b8c-87e9-03c238d4c7c8',
    name: 'Jackson Taylor',
    email: 'jackson.taylor@example.com',
    image_url: '/talent/malebartender2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'f4c7126f-d50f-4f13-b185-76d6a35cf8a0',
    name: 'Ava Turner',
    email: 'ava.turner@example.com',
    image_url: '/talent/ladybartender2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'cb8c9b22-fb5c-4e71-b66e-bfda15ee9256',
    name: 'Lucas Lee',
    email: 'lucas.lee@example.com',
    image_url: '/talent/malebartender.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'd8ce7659-0830-4c45-aab6-185b01354558',
    name: 'Mia Evans',
    email: 'mia.evans@example.com',
    image_url: '/talent/ladybartender.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'e9e77b62-24d5-4ce9-824b-2de82877d65b',
    name: 'Aiden White',
    email: 'aiden.white@example.com',
    image_url: '/talent/malebartender2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: '7ee760c5-1a18-4a87-9c93-3775dd5a6d6c',
    name: 'Chloe Harris',
    email: 'chloe.harris@example.com',
    image_url: '/talent/ladybartender2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'ad2f0077-ef0f-4c0e-9a27-47d12c163e1d',
    name: 'Noah Turner',
    email: 'noah.turner@example.com',
    image_url: '/talent/malebartender.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'db2f867f-69da-4603-8aa2-7f172f84b04a',
    name: 'Emma Robinson',
    email: 'emma.robinson@example.com',
    image_url: '/talent/ladybartender.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
  {
    id: 'e20618b2-6f99-4c50-b8b9-7f84ce2f8a9a',
    name: 'Logan Baker',
    email: 'logan.baker@example.com',
    image_url: '/talent/malebartender2.jpeg',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    talent: 'bartender',
  },
];

module.exports = {
  users,
  talents,
};
